### ISSUE TITLE
Javadoc outdated?

### ISSUE THREAD

**Issue by PascalSchumacher** [oblac/jodd-site#16]
https://jodd.org/documentation/ links to http://oblac.github.io/jodd-site/javadoc/ for javadoc. http://oblac.github.io/jodd-site/javadoc/ displays the 3.9.1 javadoc.

**Comment by igr** [comment]
True! Releasing a fix right now, everything will be set in few hours :)

**Comment by igr** [comment]
Fixed! Enjoy v4.1.1 :)

**Comment by PascalSchumacher** [comment]
Thanks!
